<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
    <RootNamespace>Highway.Storage.CrashHarness</RootNamespace>
    <AssemblyName>Highway.Storage.CrashHarness</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Highway.Server\Highway.Server.csproj" />
    <PackageReference Include="RocksDB" />
  </ItemGroup>

</Project>
