<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>Highway.Samples.OrderService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Highway.Client\Highway.Client.csproj" />
    <ProjectReference Include="..\Highway.Samples.Contracts\Highway.Samples.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\SampleConfig.cs" Link="SampleConfig.cs" />
  </ItemGroup>

</Project>
